version: '3'

services:
  rasa:
    image: rasa
    container_name: "rasa_server"
    command: bash -c 'rasa run -m models --cors "*" --debug --connector socketio --credentials "crendentials.yml" --endpoints "endpoints.yml" & rasa run actions '
    environment:
      - JWT_SECRET=<the-json-token-key-in-the-.env-file>
    ports:
      - 5005:5005
      - 5055:5055
    build:
      context: rasa_bot
      dockerfile: rasa.Dockerfile
  django:
    image: django
    container_name: "django_server"
    ports:
      - 8000:8000
    build:
      context: django_app
      dockerfile: django.Dockerfile


# Command to run : 
# docker compose -f "docker-compose.yml" up -d --build
